### ISSUE TITLE
Function Declaration: call inflight closure from inflight code

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#390] opened 2022-10-31 09:01 UTC
Our current compiler implementation wraps each inflight declaration in a file of its own. This poses a limitation and does not allow basic code reuse using functions.

Consider this simplistic code for example:
`wing test`
```ts
bring cloud;

let bucket = new cloud.Bucket();

let store_in_bucket = inflight (event: str, file: str): str => {
    bucket.put(file, event);
};

let handler1 = inflight (event: str): str => {
	store_in_bucket(event, "file1");
};     

let func1 = new cloud.Function(handler1) as "func1";

new cloud.Function(inflight () => {
    func1.invoke("hi1");
}) as "test";
```
Error message:
```sh
ReferenceError: store_in_bucket is not defined
     │     at Handler.handle (evalmachine.<anonymous>:20:3)
     │     at exports.handler (evalmachine.<anonymous>:25:5)
     │     at evalmachine.<anonymous>:27:9
     │     at Script.runInContext (node:vm:141:12)
     │     at Object.runInContext (node:vm:291:6)
     │     at /Users/urib/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:133:12
     │     at new Promise (<anonymous>)
     │     at runInSandbox (/Users/urib/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:114:12)
     │     at Object.activity (/Users/urib/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:55:24)
     └     at Object.withTrace (/Users/urib/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:82:50)
```

This code won't work currently, because the call to `store_in_bucket` inflight function is not recognized properly by the compiler.
A possible solution may be to change all inflight to be in the same file, each with a different entry.

**Comment by staycoolcall911** [comment] 2023-01-16 07:53
Should be resolved as part of #542

**Comment by staycoolcall911** [comment] 2023-02-07 09:34
@yoav-steinberg - #1448 is a duplicate of that right? It is actually defining how we are going to implement this issue if I understand correctly

**Comment by yoav-steinberg** [comment] 2023-02-14 08:09
| @yoav-steinberg - https://github.com/winglang/wing/issues/1448 is a duplicate of that right? It is actually defining how we are going to implement this issue if I understand correctly

Yes, but I'd say that #1448 is a prerequisite for implementing this issue because there still might be some plumbing to get this to work between inflight closures. See code sample:

```wing
let b = new cloud.Bucket();

let f = inflight () => { b.put("foo", "bar"); };
let f2 = inflight () => { f(); };
```
```js
resource Generated_1 { // this is f
  init(global_captured_1_b: cloud.Bucket) { 
    this.global_captured_1_b = global_captured_1_b; 
  }
  inflight run() { 
    this.global_captured_1_b.put("foo", "bar"); 
  }
}
const generated_1_instance = new Generated_1();
const f = generated_1_instance;
// end of f

// this is f2
resource Generated_2 {
  init(global_captured_1_f: Generated_1) { // f2 captures f
    this.global_captured_1_f = global_captured_1_f; 
  }
  inflight run() { 
    this.global_captured_1_f.run(); // f2 calls f
  }
}
const generated_2_instance = new Generated_2(generated_1_instance);
const f2 = generated_2_instance;
// end of f2
```

**Comment by staycoolcall911** [comment] 2023-03-28 06:35
@ekeren - is this p1?

**Comment by ekeren** [comment] 2023-03-28 08:11
I've came across this in my max-queue-size.w

Currently there is a workaround around it, creating a `cloud.IFunctionHandler` that wraps the inflight function. I think we can use this workaround for the dogfood.

But, as far as I can see,  this is P1  because that it uses the _old_ capturing mechanism that generates permissive  permissions. And we want to send the message of the beta 

What do you think?

**Comment by staycoolcall911** [comment] 2023-03-28 08:14
Yes - changed to p1.
Related to #1448

**Closed** 2023-05-22 19:13 UTC
Labels: 📜 lang-spec-impl, 🛠️ compiler
