### ISSUE TITLE
`extern` file path is resolved relative to the entrypoint directory

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4463] opened 2023-10-08 19:12 UTC
### I tried this:

`subdir/foo.w`:

```js
class Test {
  extern "./util.js" static foo(): void;
}
```

`subdir/util.js`:

```js
exports.foo = function() {};
```

Then:

```sh
wing compile subdir
```

### This happened:

```
error: Failed to resolve extern "./util.js": Not Found
  --> subdir/foo.w:2:3
  |
2 |   extern "./util.js" static foo(): void;
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Failed to resolve extern "./util.js": Not Found
```

### I expected this:

I expected the file path passed to `extern` to be relative.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-10-08 20:21
Duplicate of https://github.com/winglang/wing/issues/3916

**Closed by MarkMcCulloh** 2023-10-08 20:21 UTC
Labels: 🐛 bug
