### ISSUE TITLE
Return type inference doesn't work for optionals

### ISSUE THREAD

**Issue by eladb** [winglang/wing#7006] opened 2024-08-08 05:53 UTC
### I tried this:

```js
let x = () => {
  if true {
    return "hello";
  }

  return nil;
};
```

### This happened:

```
error: Expected type to be "nil", but got "str" instead
  --> wing/main.w:3:12
  |
3 |     return "hello";
  |            ^^^^^^^

```

### I expected this:

I expected the compiler to infer that the return type is `str?`

### Is there a workaround?

Yes, I can specify an explicit return type.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2024-08-12 14:52
Duplicate of https://github.com/winglang/wing/issues/4496

**Closed by Chriscbr** 2024-08-12 14:52 UTC
Labels: 🐛 bug, 🛠️ compiler
