### ISSUE TITLE
Rename doesn't work for struct fields

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6557] opened 2024-05-24 22:13 UTC
### I tried this:

See recording

### This happened:

https://github.com/winglang/wing/assets/598796/1b2c3d6b-348d-4f91-8ed1-369eebf22532

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2024-05-25 02:02
Dupe of #6484

**Closed by MarkMcCulloh** 2024-05-25 02:02 UTC
Labels: 🐛 bug
