### ISSUE TITLE
inflight static method should be a first class citizen

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3251] opened 2023-07-05 07:37 UTC
From https://github.com/winglang/wing/issues/3250

```ts 
bring cloud;

let api = new cloud.Api();

inflight class RequestController {
  static inflight handleRequest(request: cloud.ApiRequest): cloud.ApiResponse {
    return cloud.ApiResponse {
      status: 200,
      body: "Hello, world!"
    };
  }
}

api.get("/", RequestController.handleRequest);
```

I expected this to work

**Comment by staycoolcall911** [comment] 2023-07-09 07:05
Now that #3252 is closed, I'm closing this as duplicate of #3250, since #3250 describes the problem in a great detailed manner

**Closed by staycoolcall911** 2023-07-09 07:05 UTC
Labels: 🛠️ compiler
