### ISSUE TITLE
Support cloud.Output resource

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#2622] opened 2023-05-22 13:34 UTC
Support post deployment output artifacts, which is a feature provided by infra provisioners (TF, CF, pulumi, etc..)

Examples:
- (Terraform) https://developer.hashicorp.com/terraform/language/values/outputs
- (CloudFormation) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
- (Pulumi) https://www.pulumi.com/docs/concepts/inputs-outputs/

TODO:
- [ ] RFC a spec for the resource
- [ ] Add to SDK spec

**Comment by Chriscbr** [comment] 2023-05-22 14:14
@hasanaburayyan It looks like this is a duplicate of #2430. Closing this issue

**Closed by Chriscbr** 2023-05-22 14:14 UTC
Labels: ✨ enhancement, 🎨 sdk

**Comment by hasanaburayyan** [comment] 2023-05-22 14:16
@Chriscbr jeez how did I not find that 🤦 thanks for the catch
