### ISSUE TITLE
"As" keyword is confusing

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2519] opened 2023-05-14 11:00 UTC
### Feature Spec

Wing has an intuitive way to assign ids to resources

### Use Cases

The 'as' keyword is confusing to some devs, especially those coming from TS since it is used for casting there

### Implementation Notes

Some have requested to be able to assign id in the constructor.
I'm not sure if it's the best solution, we can also decide to keep the existing syntax, but find a way to better educate about it

### Component

Language Design

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment] 2023-05-16 13:37
Was about to create an issue. Here's a bit more context.

People who are used to constructs (cdk) might be wondering how they could specify construct ids. For them the reasoning behind the difference would be good to know:

```
let bucket = new cloud.Bucket();
let bucket1 = new cloud.Bucket() as "foo";

vs

let bucket = new cloud.Bucket();
let bucket1 = new cloud.Bucket("foo")
```

More importantly, people familiar with Typescript might be surprised about the different semantics of `as` in Typescript and Winglang.

**Comment by Chriscbr** [comment] 2024-08-22 02:32
Closing as duplicate of https://github.com/winglang/wing/issues/4604

**Closed by Chriscbr** 2024-08-22 02:32 UTC
Labels: ✨ enhancement, 📐 language-design, 🛠️ compiler, 📜 spec, needs-discussion
