### ISSUE TITLE
cloud.Service shared state between onStart and onStop

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#4228] opened 2023-09-20 12:52 UTC
### Feature Spec

You can now share a state between the time of starting a service to the time stoping it. 

This is achieved by adding a `Json` return type on the `onStart` handler and providing it as an argument to the `onStop` handler

```ts wing
bring cloud;

let service = new cloud.Service(
  onStart: inflight() : Json => {
    let port = something.listen();
	return {
        port: port
    };
  },
  onStop: inflight(state: Json) => {
    something.stop(state.port);
  },
);
```

### Use Cases

This allows, for example to close a webserver listening on a port that was obtained during start time

### Implementation Notes

Because service is a long running service, you can have a state

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by hasanaburayyan** [comment] 2023-09-21 14:53
@ekeren I think this maybe a duplicate of: https://github.com/winglang/wing/issues/4248

**Comment by staycoolcall911** [comment] 2023-09-21 15:08
I think you're right @hasanaburayyan. I'll close this one for now, because the other one has more engagement.

**Comment by staycoolcall911** [comment] 2023-09-21 15:08
Duplicates #4248

**Closed by staycoolcall911** 2023-09-21 15:08 UTC
Labels: ✨ enhancement
