### ISSUE TITLE
Inflight methods cannot reference resources not inside `this`

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2006] opened 2023-04-07 20:35 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

let b = new cloud.Bucket();

resource A {
  init() {}
  inflight do_stuff() {
    b.put("key", "value");
  }
}

let a = new A();

new cloud.Function(inflight () => {
  a.do_stuff();
}) as "test";
```

### I expected this:

The test passes.

OR I expected a compile-time error (perhaps caught with type checking / static analysis)

### Instead, this happened:

The app compiles, but running `wing test` produces an error:

```
fail ┌ ref_resource.wsim » root/env0/test
     │ ReferenceError: b is not defined
     │     at A.do_stuff (/Users/chrisr/dev/wing-test/target/test/ref_resource.wsim/.wing/clients/A.inflight.js:8:3)
     │     at Handler.handle (evalmachine.<anonymous>:20:12)
     │     at exports.handler (evalmachine.<anonymous>:25:5)
     │     at evalmachine.<anonymous>:27:9
     │     at Script.runInContext (node:vm:141:12)
     │     at Object.runInContext (node:vm:291:6)
     │     at /Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:133:12
     │     at new Promise (<anonymous>)
     │     at runInSandbox (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:114:12)
     │     at Object.activity (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:55:24)
     │     at Object.withTrace (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:69:50)
     │     at Function.invoke (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:52:29)
     │     at TestRunnerClient.runTest (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/test-runner.inflight.js:31:28)
     │     at testSimulator (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:109:39)
     │     at async testOne (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:28:13)
     └     at async test (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:17:9)
```

### Is there a workaround?

Pass the resource through the constructor, and access it via `this`

### Component:

Compiler

### Wing Version:

0.8.38

### Node.js Version:

18.14.1

### Platform(s):

MacOS

**Comment by Chriscbr** [comment] 2023-04-07 20:40
Related to implementation of #1448

**Comment by staycoolcall911** [comment] 2023-04-09 07:29
This is a similar use-case as in #1447 (cannot reference global resources from inflight), but yields a different error.
The priority is p2 because according to @eladb this is not a very useful use-case.
Closing this as duplicate of #1447.

**Closed by staycoolcall911** 2023-04-09 07:29 UTC
Labels: bug
