### ISSUE TITLE
`util.shell()` Ignores `throw: false` option

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#5348] opened 2023-12-26 22:33 UTC
### I tried this:

```sh
wing test -t tf-aws main.w
```

#### main.w
```
test "signedUrl duration option is respected" {
  let ACCESS_DENIED_ERROR = "<Error><Code>AccessDenied</Code><Message>Request has expired</Message>";
  let KEY = "tempfile.txt";
  let VALUE = "Hello, Wing!";

  bucket.put(KEY, VALUE);

  let getSignedUrl = bucket.signedUrl(KEY, { duration: 1s });

  util.sleep(2s);

  // Download file from private bucket using expired GET presigned URL
  let output = util.shell("curl \"{getSignedUrl}\"", { throw: false });

  assert(output.contains(ACCESS_DENIED_ERROR));
}
```

It makes no difference to use `throw: false` or `throw: true` as the test always passes.

### This happened:

I expected that the thrown error would halt the program execution and prevent the `assert()` from being run.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by bjrnt** [comment] 2024-02-19 23:34
After trying to reproduce this for different scenarios, I don't think this is a problem with `util.shell` but due to the way `curl` handles errors.

For example:
```ts
let api = new cloud.Api();

test "get unknown route" {
  util.shell("curl {api.url}/unknown", { throw: true });
}
```
will pass because `curl` receives a response from the server:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```
and interprets this as having successfully executed the request.

However, if you change the code slightly to be:
```ts
let api = new cloud.Api();

test "get unknown route" {
  util.shell("curl --fail {api.url}/unknown", { throw: true });
}
```
you get the desired behavior ([docs for --fail](https://curl.se/docs/manpage.html#-f)):
```
fail ┌ main.wsim » root/env3/test:get unknown route
     │ Error: Error executing command "curl --fail http://127.0.0.1:64383/unknown". Exited with error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
     │                                  Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     │ curl: (22) The requested URL returned error: 404
```

**Comment by staycoolcall911** [comment] 2024-02-21 06:32
Thanks for explaining @bjrnt . I'll close this issue then.

**Closed** 2024-02-21 06:32 UTC
Labels: 🐛 bug, 🎨 sdk, good first issue
