### ISSUE TITLE
Function Types: independent phase functions

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#474] opened 2022-11-07 07:53 UTC
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#113-function-types

We should add support for functions that can run both preflight and inflight. Phase independent closure literal is `=>` (where for inflight it is `~>` and for preflight it is `->`).

**Comment by Chriscbr** [comment] 2023-06-23 22:30
Duplicate of #435 (I think one of the issues was just meant to be about the syntax vs the feature design itself, but it makes sense to group them together for now)

**Closed by Chriscbr** 2023-06-23 22:30 UTC
Labels: 📜 lang-spec-impl, 🛠️ compiler
