### ISSUE TITLE
compiler: Dynamic resource creation leads to duplicated name error

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3910] opened 2023-08-21 15:04 UTC
### I tried this:

```
bring cloud;

class Foo {
  init() {}

  bar(path: str, location: str) {
    new cloud.Function(inflight () => {}) as "redirect.${path}.${location}.onDeploy.smokeTest";
  }
}

let foo = new Foo();
foo.bar("/", "https://www.example.com/");
foo.bar("/foo", "https://www.example.com/foo");
```

see [playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAGMAbABhAHMAcwAgAEYAbwBvACAAewAKACAAIABpAG4AaQB0ACgAKQAgAHsAfQAKAAoAIAAgAGIAYQByACgAcABhAHQAaAA6ACAAcwB0AHIALAAgAGwAbwBjAGEAdABpAG8AbgA6ACAAcwB0AHIAKQAgAHsACgAgACAAIAAgAG4AZQB3ACAAYwBsAG8AdQBkAC4ARgB1AG4AYwB0AGkAbwBuACgAaQBuAGYAbABpAGcAaAB0ACAAKAApACAAPQA%2BACAAewB9ACkAIABhAHMAIAAiAHIAZQBkAGkAcgBlAGMAdAAuACQAewBwAGEAdABoAH0ALgAkAHsAbABvAGMAYQB0AGkAbwBuAH0ALgBvAG4ARABlAHAAbABvAHkALgBzAG0AbwBrAGUAVABlAHMAdAAiADsACgAgACAAfQAKAH0ACgAKAGwAZQB0ACAAZgBvAG8AIAA9ACAAbgBlAHcAIABGAG8AbwAoACkAOwAKAGYAbwBvAC4AYgBhAHIAKAAiAC8AIgAsACAAIgBoAHQAdABwAHMAOgAvAC8AdwB3AHcALgBlAHgAYQBtAHAAbABlAC4AYwBvAG0ALwAiACkAOwAKAGYAbwBvAC4AYgBhAHIAKAAiAC8AZgBvAG8AIgAsACAAIgBoAHQAdABwAHMAOgAvAC8AdwB3AHcALgBlAHgAYQBtAHAAbABlAC4AYwBvAG0ALwBmAG8AbwAiACkAOwA%3D)

### This happened:

```
Failed to compile.

ERROR: There is already a Construct with name '$Closure1' in Foo [Foo]

hint: Every preflight object needs a unique identifier within its scope. You can assign one as shown:

> new cloud.Bucket() as "MyBucket";

For more information, see https://www.winglang.io/docs/concepts/resources

wing/target/test.wsim.082901.tmp/.wing/preflight.js:17
           class $Closure1 extends $stdlib.std.Resource {
             constructor(scope, id, ) {
>>             super(scope, id);
               this._addInflightOps("handle", "$inflight_init");
               this.display.hidden = true;
```

The suggested solution of `> new cloud.Bucket() as "MyBucket";` doesn't seem to work with dynamic references like `    new cloud.Function(inflight () => {}) as "redirect.${path}.${location}.onDeploy.smokeTest";`

### I expected this:

No error or a more helpful error message

### Component

Compiler

### Wing Version

0.25.30

### Node.js Version

v18.17.0

### Platform(s)

MacOS

### Anything else?

when creating only one resource, the generated resource name seems to be correct

```
{
  "Foo_redirect--https----wwwexamplecom--onDeploysmokeTest_CE5EB5C1": {
    "//": {
      "metadata": {
        "path": "root/Default/Default/Foo/redirect.--.https:----www.example.com--.onDeploy.smokeTest/Default",
        "uniqueId": "Foo_redirect--https----wwwexamplecom--onDeploysmokeTest_CE5EB5C1"
      }
    },
    "environment": {
      "variables": {
        "WING_FUNCTION_NAME": "redirect----https-----www-example-com---onDeploy-smokeT-c8901fa3",
        "WING_TARGET": "tf-aws"
      }
    },
    "function_name": "redirect----https-----www-example-com---onDeploy-smokeT-c8901fa3",
    "handler": "index.handler",
    "publish": true,
    "role": "${aws_iam_role.Foo_redirect--https----wwwexamplecom--onDeploysmokeTest_IamRole_74AEC3EF.arn}",
    "runtime": "nodejs18.x",
    "s3_bucket": "${aws_s3_bucket.Code.bucket}",
    "s3_key": "${aws_s3_object.Foo_redirect--https----wwwexamplecom--onDeploysmokeTest_S3Object_C1D7BB11.key}",
    "timeout": 30,
    "vpc_config": {
      "security_group_ids": [],
      "subnet_ids": []
    }
  }
}
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment] 2023-08-21 15:06
Just for reference, something this works of course

```
bring cloud;
bring http;

class Foo {
  init(path: str, location: str) {
    new cloud.Function(inflight () => {}) as "redirect.${path}.${location}.onDeploy.smokeTest";
  }
}

new Foo("/", "https://www.example.com/") as "one";
new Foo("/foo", "https://www.example.com/foo") as "two";
```

but sort of defeats the purpose

**Comment by staycoolcall911** [comment] 2023-08-23 14:55
Thanks for reporting @skorfmann, I believe this is a duplicate of #2853, please reopen if I'm mistaken.

**Closed by staycoolcall911** 2023-08-23 14:55 UTC
Labels: 🐛 bug
