### ISSUE TITLE
Wing Console starts the app twice which can cause unexpected issues

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5349] opened 2023-12-27 08:10 UTC
### I tried this:

```sh
wing run
```

### This happened:

It seems like Wing Console starts the simulated app twice. This can cause issues related to shared resources such as open ports, and may also be a cause for performance issues.

The console server creates two instances of the simulator - one for the app and one for test (see [here](https://github.com/winglang/wing/blob/6d98fb7d428c4c2620209f41af8828e87f34c230/apps/wing-console/console/server/src/index.ts#L144)). I don't think the test simulator needs to be started because there's an app instance started for each individual test.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment] 2023-12-27 16:29
This is causing serious DX issues with my bedrock workshop code (cause I use ngrock) as well for github webhooks.

@ainvoner, do you all know how complicated is fixing this?

**Comment by ainvoner** [comment] 2023-12-28 07:00
@ekeren need to check... look at #5164

**Comment by ekeren** [comment] 2023-12-28 10:27
@eladb advice was to add 
```ts
    if !std.Node.of(this).app.isTestEnvironment {
```

Before start ngrok. It Works!

**Comment by ainvoner** [comment] 2023-12-28 11:13
> @eladb advice was to add
> 
> ```ts
>     if !std.Node.of(this).app.isTestEnvironment {
> ```
> 
> Before start ngrok. It Works!

we need to do the same in Wing Cloud :)

**Comment by Chriscbr** [comment] 2024-01-02 20:07
@ekeren @ainvoner Can you share more specifics on what issues are occurring, or share a minimal repro perhaps? This website has some useful pointers: http://sscce.org/

**Comment by ekeren** [comment] 2024-01-02 20:29
The console start the simulator twice, which cause issues if you are using some singletonish resource like a static port or ngrock. Because ngrock free version limits you to a single instance "Your account is limited to 1 simultaneous ngrok agent session." 

@eladb explains the root cause under the  "This happened:" section 
> It seems like Wing Console starts the simulated app twice. This can cause issues related to shared resources such as open ports, and may also be a cause for performance issues.
The console server creates two instances of the simulator - one for the app and one for test (see [here](https://github.com/winglang/wing/blob/6d98fb7d428c4c2620209f41af8828e87f34c230/apps/wing-console/console/server/src/index.ts#L144)). I don't think the test simulator needs to be started because there's an app instance started for each individual test.

**Comment by Chriscbr** [comment] 2024-01-02 21:06
> The console start the simulator twice, which cause issues if you are using some singletonish resource like a static port or ngrock. Because ngrock free version limits you to a single instance "Your account is limited to 1 simultaneous ngrok agent session."

It's not clear to me how these worked in the past -- even before the changes to the console/simulator were made, I imagine apps that hard-coded ports like the one below would have probably failed since we model tests as isolated environments that each get a fresh copy of the app's resources:

```js
bring ex;

let app = new ex.ReactApp(localPort: 3000);

test "test1" {
  assert(2 + 2 == 4);
}

test "test2" {
  assert(3 + 3 = 6);
}

// "wing test" error: port 3000 is already taken
```

**Comment by ekeren** [comment] 2024-01-02 21:17
Right. 
In the above example you couldn't create tests, because it will not work. (which is, IMO, an issue of the ReactApp resource) 

Today, after the change, even if you don't have a test the above example will not work.
That is the main difference

**Comment by Chriscbr** [comment] 2024-01-02 21:28
> I don't think the test simulator needs to be started because there's an app instance started for each individual test.

I'm not sure what this means @eladb?

I suppose when you try running tests in Wing Console, we could stop the main simulator, start the test simulator, execute the tests, stop that simulator, and restart the main simulator. But I'm not sure whether it's the right solution.

re: singletons -- I'm wondering if we're missing a way in Winglang to express these two different concepts / use cases:

1. defining objects that can only be created once in your **logical application**
2. defining objects that can only be created once per **host system** or **cloud account**

(1) represents the general singleton pattern from the OO world -- instead of multiple clients or factories or buckets, I want to centralize information or state through a single client or factory or bucket etc. If each unit test runs in an isolated copy of the app, the singleton will be created once per test since they're logically independent apps.
(2) represents a solution to limitations of the real world -- for example, you can only have 1 free ngrok instance, or 1 free postgres on http://neon.tech, etc. If multiple copies of the app are running and using the same resource, it the responsibility of the user to make sure it behaves as expected.

(2) can be thought of as a "global singleton" in some sense

**Comment by ainvoner** [comment] 2024-01-04 11:20
> (2) represents a solution to limitations of the real world -- for example, you can only have 1 free ngrok instance, or 1 free postgres on http://neon.tech/, etc. If multiple copies of the app are running and using the same resource, it the responsibility of the user to make sure it behaves as expected.

I agree it is the responsibility of the user if they deliberately run two instances of the same simulator. When users run a single instance (from their point of view) of the simulator they are not expecting those kind of issues.

**Comment by skyrpex** [comment] 2024-07-08 07:44
As you may know, the console currently creates two simulators during start: the simulator used to run the app, and the simulator used for executing the tests.

We could make it so the test simulator is created just before executing any tests, and is stopped afterwards, freeing the user's computer from unnecessary resource consumption (at the cost of a slower test execution). To be honest, it's really confusing to start the console with some containers and API, and seeing x2 containers and x2 APIs up and running.

This change doesn't handle the fixed ports issue, although it's not really a wing-specific issue. You can have the same sort of problems in any language when it comes to testing your application in parallel.

**Comment by polamoros** [comment] 2024-07-08 11:03
@skyrpex, we need to run the test simulator at the start to list the tests. We should then save this information in the testsStateManager to avoid needing to run the test simulator again for listing them.

As you suggested, we should restart/stop the test simulator for each test execution.

**Comment by skyrpex** [comment] 2024-07-15 09:34
Pol's PR https://github.com/winglang/wing/pull/6876 added lazy instantiation of the simulator, so the issues like using a fixed port (e.g. `new React(port: 3000)`) are now easier to understand: the error message "port 3000 already in use" makes sense now as it's part of the test execution.

I think we can close this issue now as there's nothing else we can really do other than promoting using random/free ports everywhere as the best practice.

**Closed by skyrpex** 2024-07-15 09:34 UTC
Labels: 🐛 bug, 🕹️ simulator, 🛫 console
