### ISSUE TITLE
`?.` not really working?!

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6034] opened 2024-03-21 18:55 UTC
### I tried this:

```js
let map: Map<str>? = nil;
map?.entries();
```

Another example:

```js
let x: Array<str>? = nil;
let y = x?.at(0) ?? "hello";
```

### This happened:

```
Error: Cannot convert undefined or null to object
  --> wing/main.w:2:1
  | let map: Map<str>? = nil;
2 | map?.entries();
  | ^
at /app/wing/main.w:2:1
```

And:

```
Error: Cannot read properties of undefined (reading 'length')
  --> wing/main.w:2:1
  | let map: Map<str>? = nil;
2 | map?.entries();
  | ^
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2024-03-21 19:07
dupe of https://github.com/winglang/wing/issues/4470

**Closed by MarkMcCulloh** 2024-03-21 19:07 UTC
Labels: 🐛 bug
