### ISSUE TITLE
empty multiline string breaks the compiler

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4816] opened 2023-11-06 21:59 UTC
### I tried this:

add a multiline string with no content 

```
destroy.addOverride("provisioner.local-exec.command", "
");
```

rung `wing compile -t tf-aws`

### This happened:

```
ERROR: Invalid or unexpected token
```

due to 

```
      (destroy.addOverride("provisioner.local-exec.command", "
      "));
```

### I expected this:

no error

### Component

Compiler

### Wing Version

0.44.11

### Node.js Version

18.17.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment] 2023-11-06 22:09
looks like this applies to this as well

```
destroy.addOverride("provisioner.local-exec.command", "
foo bar
");
```

**Comment by staycoolcall911** [comment] 2023-11-08 12:50
@skorfmann - I'm closing this as a duplicate of #4375.
If you disagree please reopen.
If you decide to reopen - please update the example to a standalone one that could be easily reproduced (if possible). Thanks

**Closed by staycoolcall911** 2023-11-08 12:50 UTC
Labels: 🐛 bug
