### ISSUE TITLE
Missing method-agnostic route for `cloud.Api`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6146] opened 2024-04-04 12:27 UTC
### Use Case

I'd like to be able to do something like this:

```js
let api = new cloud.Api();
let createRoute = (method: str) => {
  api.onRequest(method, inflight () => {
    return { body: "called {method}" };
  });
};
```

### Proposed Solution

See above

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment] 2024-04-04 14:19
Duplicate of https://github.com/winglang/wing/issues/1848

**Closed by Chriscbr** 2024-04-04 14:19 UTC
Labels: ✨ enhancement, needs-discussion
