### ISSUE TITLE
can't bring a module file that has test

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3571] opened 2023-07-23 11:51 UTC
#### `./f1.w`
```ts wing
bring "./f2.w" as f2;

f2.F2.hello();
```

#### `./f2.w`
```ts wing
class F2{
  static hello() {
    log("Hello");
  }
}

test "main"{
 }
```

### This happened:

```
error: Cannot bring ""./f2.w"" - modules with statements besides classes, interfaces, enums, and structs cannot be brought


error: Expected identifier "f2" to be a variable, but it's a namespace
  --> f1.w:3:1
  |
3 | f2.F2.hello();
  | ^^ Expected identifier "f2" to be a variable, but it's a namespace
```

### I expected this:

to work

### Is there a workaround?

remove the test

### Component

Language Design

### Wing Version

0.24.41

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment] 2023-11-16 10:05
This is basically a duplicate of a part of #4653 and will be resolved when #4653 is done.

**Closed by staycoolcall911** 2023-11-16 10:05 UTC
Labels: 🐛 bug, 🛠️ compiler, 🧪 testing, 📚 libraries
