### ISSUE TITLE
extern file path is relative to main.w executable file and not to the file it is used in

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#4243] opened 2023-09-21 11:27 UTC
### I tried this:

this is a directory structure:

>src/
> - main.w
>> dnsimple/
>> - dnssimple.w
>> - util.js

in dnsimple.w:
```
  extern "./util.js" static toResource(o: constructs.IConstruct): Dummy;
```
run `wing it`

### This happened:

![Screenshot 2023-09-21 at 14 25 13](https://github.com/winglang/wing/assets/2538825/994f36d9-238e-4ff9-b1fe-0066ef2a3a39)

### I expected this:

to work

### Is there a workaround?

use a path relative to the main.w file
```
  extern "./src/reverse-proxy/util.js" static toResource(o: constructs.IConstruct): Dummy;
```

### Component

Compiler

### Wing Version

0.13.35

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-09-21 21:57
Dupe of #3916

**Closed by MarkMcCulloh** 2023-09-21 21:57 UTC
Labels: 🐛 bug, 🛠️ compiler
