### ISSUE TITLE
`wing test` runs code multiple times

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3917] opened 2023-08-22 02:59 UTC
### I tried this:

I noticed that something weird was happening on [THIS](https://github.com/winglang/wing/blob/main/examples/tests/sdk_tests/std/json.w) file. Every time I run `wing test` on it, the code would execute twice. I could see that for the first time when I added a `log()` to che code.

To figure out what was going on, I kept slimming down the code till I found the culprit: code outside `test` blocks gets executed as many times as the number of tests present in your file.

### This happened:

Create a `.w` file with this content:
```
test "a" {
}

test "b" {
}

test "c" {
}

log("test");
```
Run `wing test` on it.

Shell output:
```sh
test
test
test
```

### I expected this:

I expected shell to print only once:
```sh
test
```

### Component

SDK

### Wing Version

0.25.20

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment] 2023-08-22 08:13
I think that's by design, tests are spinning up a full version of the app per test. I agree that this is unexpected and certainly has limits. While it might work okish for the simulator target, users will hit a wall quickly when testing against any of the cloud providers. See https://github.com/winglang/wing/issues/3168 as well.

**Comment by staycoolcall911** [comment] 2023-08-31 09:58
@garysassano - thank you so much for reporting this. We have discussed this internally in the compiler/sdk team and will address the issue.
We'll use #3168 as the issue to communicate our strategy around the design change necessary in order to fix this, so I'm closing this issue as duplicate for now.

**Closed by staycoolcall911** 2023-08-31 09:58 UTC
Labels: 🐛 bug, 🎨 sdk
