### ISSUE TITLE
`cloud.Function` is timing out during a debugging session

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6063] opened 2024-03-26 08:45 UTC
### I tried this:

Debug a `cloud.Function`

### This happened:

The timeout caused my app to stop mid-flight

### I expected this:

When a debugger is attached, we should disable the timeout in the simulator

### Is there a workaround?

Manually set the timeout?

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2024-03-26 14:51
Duplicate of #5986

**Closed by Chriscbr** 2024-03-26 14:51 UTC
Labels: 🐛 bug
