### ISSUE TITLE
dependency cycle error 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1757] opened 2023-03-09 09:25 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

tried compiling the following command:

```ts (wing)
bring cloud;

resource MyStronglyPerssistentQueue {
  q: cloud.Queue;
  b: cloud.Bucket; 
  
  init() {
    this.q = new cloud.Queue();
    this.b = new cloud.Bucket();
    this.q.on_message((inflight (m: str) => {
      this.b.put("some", "thing");
    }));
  }

  inflight push(m: str) {
    this.q.push(m);
  }
}

let pq = new MyStronglyPerssistentQueue();
```

```sh
wing compile -t sim a.w
```

### I expected this:

to compile

### Instead, this happened:

```sh
wingly % wing compile -t sim a.w
preflight error: Dependency cycle detected: root/MyStronglyPerssistentQueue/cloud.Queue => root/MyStronglyPerssistentQueue/cloud.Queue-OnMessage-bf0e28e4 => root/MyStronglyPerssistentQueue/cloud.Queue

  note: intermediate javascript code (/private/tmp/wingly/target/.wing/preflight.js):
   }
   }
>> new MyApp().synth();
  note: run with `NODE_STACKTRACE=1` environment variable to display a stack trace
```

### Component:

Compiler

### Wing Version:

 0.5.104

### Anything else?

It probably related to the cartesian permission matrix we currently have and might be resolved with https://github.com/winglang/wing/pull/1743

**Comment by Chriscbr** [comment] 2023-03-09 19:26
Duplicate of #1700

**Closed by Chriscbr** 2023-03-09 19:26 UTC
Labels: bug
