### ISSUE TITLE
compiler crash when importing cdk types

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#5933] opened 2024-03-13 10:40 UTC
### I tried this:

```wing
bring "aws-cdk-lib" as cdk;

let eventBridge = new cdk.aws_events.EventBus(eventBusName: "test") as "EventBridge";
let rule = new cdk.aws_events.CfnRule(
  name: "test",
  eventBusName: eventBridge.eventBusName,
  eventPattern: {},
  targets: [{
    arn: "",
    id: "",
  }],
);
new cdk.aws_events.Rule(eventPattern: {
  detailType: [""],
});
```

### This happened:

```
Panicked, backtrace not captured: Unsupported
error: Compiler bug during type-checking ('panicked at libs/wingc/src/type_check/jsii_importer.rs:250:21:
Tried importing aws-cdk-lib.aws_events.CfnRule.BatchParametersProperty but CfnRule already defined as a type'), please report at https://www.winglang.io/contributing/start-here/bugs
   --> main.w:13:1
   |  
13 | / new cdk.aws_events.Rule(eventPattern: {
14 | |   detailType: [""],
15 | | });
   | \--^ Compiler bug during type-checking ('panicked at libs/wingc/src/type_check/jsii_importer.rs:250:21:
Tried importing aws-cdk-lib.aws_events.CfnRule.BatchParametersProperty but CfnRule already defined as a type'), please report at https://www.winglang.io/contributing/start-here/bugs
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2024-03-13 13:00
Dupe of #5507, added your example to that issue to help with search-ability

**Closed by MarkMcCulloh** 2024-03-13 13:00 UTC
Labels: 🐛 bug
