### ISSUE TITLE
Unable to call static inflight methods from inflight context

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1748] opened 2023-03-07 20:22 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

resource Foo {
  static inflight hello_inflight(): num {
    print("hello, inflight");
    return 42;
  }

  init() { }
}

resource Bar {
  foo: Foo;

  init () {
    this.foo = new Foo();
  }

  inflight dang() {
    let r = Foo.hello_inflight();
    assert(r == 42);
  }
}

let b = new Bar();

new cloud.Function(inflight () => {
  b.dang();
});
```

### I expected this:

For `wing test` to pass.

### Instead, this happened:

```
preflight error: Failed to bundle function: ✘ [ERROR] Expected "(" but found "hello_inflight"

    ../../../../../../private/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-test-awTwuG/.wing/clients/Foo.inflight.js:6:13:
      6 │ async static hello_inflight()  {
        │              ~~~~~~~~~~~~~~
        ╵              (

/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:2095
      throw reject;
      ^

Error: Build failed with 1 error:
../../../../../../private/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-test-awTwuG/.wing/clients/Foo.inflight.js:6:13: ERROR: Expected "(" but found "hello_inflight"
    at failureErrorWithLog (/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:1626:15)
    at /Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:1038:25
    at /Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:983:52
    at buildResponseToResult (/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:1036:7)
    at /Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:1065:16
    at responseCallbacks.<computed> (/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:687:9)
    at handleIncomingPacket (/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:742:9)
    at Socket.readFromStdout (/Users/eladb/code/wing4/libs/wingsdk/node_modules/esbuild-wasm/lib/main.js:663:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 13,
        file: '../../../../../../private/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-test-awTwuG/.wing/clients/Foo.inflight.js',
        length: 14,
        line: 6,
        lineText: 'async static hello_inflight()  {',
        namespace: '',
        suggestion: '('
      },
      notes: [],
      pluginName: '',
      text: 'Expected "(" but found "hello_inflight"'
    }
  ],
  warnings: []
}

Node.js v18.12.1


  note: intermediate javascript code (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-test-awTwuG/.wing/preflight.js):
     Bar._annotateInflight("dang", {});
     const b = new Bar(this,"Bar");
>>   this.node.root.newAbstract("@winglang/sdk.cloud.Function",this,"cloud.Function",new $stdlib.core.Inflight(this, "$Inflight1", {
       code: $stdlib.core.NodeJsCode.fromFile(require('path').resolve(__dirname, "proc.90611c58732c82bcb432fff4f534c6c8e142ca336a2089629e4d50573a527de7/index.js").replace(/\\/g, "/")),
       bindings: {
  note: run with `NODE_STACKTRACE=1` environment variable to display a stack trace
```

### Component:

Compiler

**Comment by staycoolcall911** [comment] 2023-03-08 09:16
The error is thrown [here](https://github.com/winglang/wing/blob/a36c28d4d5aa3cbfc3636ce02a84e5876ff5edc1/libs/wingsdk/src/cloud/function.ts#L131). Looks like esbuild fails for `static` functions.

**Comment by staycoolcall911** [comment] 2023-03-13 07:32
Duplicate of #1669

**Closed by staycoolcall911** 2023-03-13 07:32 UTC
Labels: bug
