### ISSUE TITLE
Impossible to define `test`s within non-entrypoint files

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3579] opened 2023-07-23 19:24 UTC
### I tried this:

Let's create a module `calc.w`:

```js
class Calc {
  static inflight add(l: num, r: num): num { return l + r; }
}

test "add two numbers" {
  assert(Calc.add(1, 2) == 3);
}
```

Now, let's use this module:

`main.w`:

```js
bring "./calc.w" as calc;

test "use Calc" {
  assert(calc.Calc.add(1, 1) == 2);
}
```

### This happened:

```
modules with statements besides classes, interfaces, enums, and structs cannot be brought
```

### I expected this:

I expected tests to be something that I can define everywhere...

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment] 2023-07-23 19:25
Naturally I understand why this happens (because tests are `cloud.Function`s), but that's not a good excuse :-).

**Comment by Chriscbr** [comment] 2023-07-23 19:30
Duplicate of https://github.com/winglang/wing/issues/3571

**Closed** 2023-07-23 19:30 UTC
Labels: 🐛 bug
