### ISSUE TITLE
The `tree.json` file always shows all possible connections

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#1084] opened 2023-01-09 18:31 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Compile the following code using `wing compile -t sim file.w`:

```
bring cloud;

let bucket = new cloud.Bucket();
let counter = new cloud.Counter();

/**
 * Adds a task to the task list.
 * @returns The ID of the new task
 */
let add_task = new cloud.Function(inflight (title: str): str => {
  let id = counter.inc();
  print("adding task ${id} with title: ${title}");
  bucket.put("${id}", title);
  return "${id}";
}) as "add_task";
```

### I expected this:

The `tree.json` should indicate that the `root/add_task` resource has a connection with `root/cloud.Bucket::put, as follows:

```json
{
      "cloud.Bucket": {
        "id": "cloud.Bucket",
        "path": "root/cloud.Bucket",
        "attributes": {
          "wing:resource:connections": [
            {
              "direction": "inbound",
              "relationship": "put",
              "resource": "root/add_task",
              "implicit": false
            }
          ]
        }
      }
}
```

### Instead, this happened:

The compiler outputs all of the possible connections to the bucket:

```json
{
      "cloud.Bucket": {
        "id": "cloud.Bucket",
        "path": "root/cloud.Bucket",
        "attributes": {
          "wing:resource:connections": [
            {
              "direction": "inbound",
              "relationship": "delete",
              "resource": "root/add_task",
              "implicit": false
            },
            {
              "direction": "inbound",
              "relationship": "get",
              "resource": "root/add_task",
              "implicit": false
            },
            {
              "direction": "inbound",
              "relationship": "list",
              "resource": "root/add_task",
              "implicit": false
            },
            {
              "direction": "inbound",
              "relationship": "put",
              "resource": "root/add_task",
              "implicit": false
            }
          ]
        }
      }
}
```

### Component:

Compiler, SDK

### Wing Version:

0.4.64

### Node.js Version:

18.12.1

### Platform(s):

MacOS

**Comment by Chriscbr** [comment] 2023-01-09 18:41
Thanks for reporting this, indeed the metadata is incorrect. Today the compiler lists all possible methods whenever a resource is captured as a workaround until we can add static analysis to track which methods are called within an inflight.
See the comment here: https://github.com/winglang/wing/blob/88b39204f4644931df24552d134810f4e4aad4a5/libs/wingc/src/capture.rs#L236-L238

This is definitely something we should fix before Wing 1.0. In the interim maybe we can show some placeholder instead of the exact method names in the console?

**Comment by skyrpex** [comment] 2023-01-09 18:51
Cool to know! Until then, we can reduce the connections to a single, unnamed connection. That will do :)

**Comment by staycoolcall911** [comment] 2023-01-30 14:13
Closing as duplicate of #76 - @skyrpex please reopen if you think this is needed as a separate issue

**Closed by staycoolcall911** 2023-01-30 14:13 UTC
Labels: bug
