### ISSUE TITLE
public struct can reference non public struct and interfaces

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5255] opened 2023-12-19 12:44 UTC
### I tried this:

Notice that api.w public A struct is composed of a private I interface and a private B struct.
Should this be legal? 
### `api.w`
```ts
struct B{

}
interface I {
  foo():void;
}
pub struct A {
  b: B;
  i: I?;
}
```

### `main.w`
```ts
bring "./api.w" as a;

let a1 = a.A {
  b: {}
};

a1.i?.foo();
```

### This happened:

Everything compile

### I expected this:

Not to compile and complain about the fact that I am including a private API as part of my public API 

### Is there a workaround?

look the other way

### Wing Version

0.52.7

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2023-12-20 18:25
Duplicate of https://github.com/winglang/wing/issues/4655

**Closed by Chriscbr** 2023-12-20 18:25 UTC
Labels: 🐛 bug, 🛠️ compiler
