### ISSUE TITLE
There is no intellisense on strings

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2712] opened 2023-05-30 15:46 UTC
### I tried this:

```ts
let s = "hello";
s.
```

### This happened:

Nothing

### I expected this:

To get intellisense on the string, showing me that I can use string functions like `uppercase()`, `lowercase`, etc.

### Component

Compiler

### Wing Version

0.17.44

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment] 2023-05-30 16:03
Great minds... @ShaiBer, @skorfmann 
Marking this issue as a duplicate of #2711

**Closed** 2023-05-30 16:03 UTC
Labels: 🐛 bug
