### ISSUE TITLE
Bring CDKTF is broken

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2960] opened 2023-06-19 08:37 UTC
### I tried this:

```
bring cloud;
bring "cdktf" as cdktf;

```

with

```
"node_modules/cdktf": {
      "version": "0.16.3",
```

doesn't seem to be cdktf version dependent though.

```
wing compile -t tf-aws main.w
```

### This happened:

```
panicked, backtrace not captured: Unsupported
Error: error: Compiler bug (panicked at 'assertion failed: param.name == \"id\"', libs/wingc/src/type_check/jsii_importer.rs:676:29) during type-checking, please report at https://docs.winglang.io/contributors/bugs
  --> main.w:2:1
  |
2 | bring "cdktf" as cdktf;
  | ^^^^^^^^^^^^^^^^^^^^^^^ Compiler bug (panicked at 'assertion failed: param.name == \"id\"', libs/wingc/src/type_check/jsii_importer.rs:676:29) during type-checking, please report at https://docs.winglang.io/contributors/bugs


    at compile (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/compile.js:87:19)
```

### I expected this:

it compiles

### Component

Compiler

### Wing Version

0.21.14

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment] 2023-06-19 08:41
looks like the latest working version is `winglang@0.21.5` and it's broken since `winglang@0.21.6`

**Comment by staycoolcall911** [comment] 2023-06-19 08:45
Thanks @skorfmann - I think this is duplicate of the recently introduced #2934.
I believe this will be fixed in the next few days by @yoav-steinberg, but feel free to remind us if it is not fixed by Thursday

**Closed by staycoolcall911** 2023-06-19 08:45 UTC
Labels: 🐛 bug
