### ISSUE TITLE
Unknown error: Unexpected keyword 'this' (runtime) when referencing a preflight field inside inflight

### ISSUE THREAD

**Issue by flyingImer** [winglang/wing#2215] opened 2023-04-22 23:48 UTC
### I tried this

```
bring cloud;

resource MyResource {
    _threshold: num;
    _queue: cloud.Queue;
    init(threshold: num) {
        this._queue = new cloud.Queue();
        this._threshold = threshold;
        this._queue.add_consumer(inflight (message: str) => {
            log("got message ${this._threshold}");
        });
    }
}

new MyResource(10);

resource YourResource {
    _threshold: num;
    _queue: cloud.Queue;
    init(threshold: num) {
        this._queue = new cloud.Queue();
        this._threshold = threshold;
    }

    public add_consumer() {
        this._queue.add_consumer(inflight (message: str) => {
            log("got message ${this._threshold}");
        });
    }
}

let r = new YourResource(10);
r.add_consumer();
```

### I expected this:

to work

### Instead, this happened

`Unknown error: Unexpected keyword 'this'` when the queue handles a message

### Is there a workaround?

```
bring cloud;

resource MyResource {
    _threshold: num;
    _queue: cloud.Queue;
    init(threshold: num) {
        this._queue = new cloud.Queue();
        this._threshold = threshold;
        this._queue.add_consumer(inflight (message: str) => {
            log("got message ${threshold}"); // <- use the passed in variable directly
        });
    }
}

new MyResource(10);
```

### Component

Compiler

### Wing Version

0.13.15

### Node.js Version

v18.14.0

### Platform(s)

MacOS

### Anything else?

It seems `this` is not properly handled.

pre-bundled code snippet for sim:
```
return class Handler {
  constructor(clients) {
    for (const [name, client] of Object.entries(clients)) {
      this[name] = client;
    }
  }
  async handle(message) {
  const { this } = this; // <- this line is problematic
  {console.log(`got message ${this._threshold}`)};
}
};
```

bundled code snippet for tf-aws:
```
return class Handler {
      constructor(clients) {
        for (const [name, client] of Object.entries(clients)) {
          this[name] = client;
        }
      }
      async handle(message) {
        const { this: this2 } = this; // <- this line seems to be problematic
        {
          console.log(`got message ${this._threshold}`); // or probably this one, it works if manually change to `this2._threshold`
        }
        ;
      }
    };
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment] 2023-04-23 13:23
Thanks for reporting EJ, I believe `this` is a duplicate of #1966. Closing

**Closed by staycoolcall911** 2023-04-23 13:23 UTC
Labels: 🐛 bug
