### ISSUE TITLE
`wing compile .` panics

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4462] opened 2023-10-08 19:07 UTC
### I tried this:

Run `wing compile .`

### This happened:

```
error: Compiler bug (panicked at 'called `Option::unwrap()` on a `None` value', libs/wingc/src/type_check.rs:3009:19) during type-checking, please report at https://www.winglang.io/contributing/start-here/bugs
```

### I expected this:

To work

### Component

Compiler, CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-10-08 20:22
Duplicate of https://github.com/winglang/wing/issues/4431

**Closed by MarkMcCulloh** 2023-10-08 20:22 UTC
Labels: 🐛 bug
