### ISSUE TITLE
Include winglibs docs on the docsite

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5225] opened 2023-12-14 21:49 UTC
### Use Case

Include winglibs in our docs

### Proposed Solution

Add a new section in the sidebar for "Winglibs" perhaps?

Then we can set up some automation to periodically copy READMEs of packages from https://github.com/winglang/winglibs into the `winglang/wing` repo, inside the appropriate docs/ subfolder.

### Component

Documentation, Libraries

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by boyney123** [comment] 2024-06-24 08:35
Hey @Chriscbr 

Seems like a duplicate of #6429? Should we close one of these?

**Comment by staycoolcall911** [comment] 2024-06-24 09:01
I'll go ahead and close this one, since #6429 has a discussion going in it.

**Closed by staycoolcall911** 2024-06-24 09:01 UTC
Labels: 📚 documentation, ✨ enhancement, 📚 libraries
