### ISSUE TITLE
Enforce serializable types for inflight methods on preflight classes

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6475] opened 2024-05-14 20:40 UTC
The motivation would be to add a constraint so that we can guarantee inflight methods on preflight classes can be safely called from other language runtimes.

We may also want to consider where we don't need to enforce this -- for example, perhaps private methods and fields can be allowed to use non-serializable types.

**Comment by staycoolcall911** [comment] 2024-06-24 07:49
Related issue about the simulator: #4510

**Comment by staycoolcall911** [comment] 2024-06-24 08:54
I'll go ahead and close as duplicate of #4510. Will add this issue description there as a comment.

**Closed by staycoolcall911** 2024-06-24 08:54 UTC
Labels: 📐 language-design, 🛠️ compiler, needs-discussion
