### ISSUE TITLE
No error when closure doesn't return a value

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2228] opened 2023-04-24 06:49 UTC
### I tried this

```js
bring cloud;

resource WebHook {
  api: cloud.Api;

  init() {
    this.api = new cloud.Api();
    this.api.post("/", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
      log(Json.stringify(req));
    });
  }
}
```

### I expected this:

A compiler error that tells me that the inflight closure must return a value of type `cloud.ApiResponse`

### Instead, this happened

No error

### Is there a workaround?

N/A

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment] 2023-04-24 09:41
This seems to be a duplicate of #457

**Closed** 2023-04-24 09:41 UTC
Labels: 🐛 bug
