### ISSUE TITLE
Allow sorting with Arrays

### ISSUE THREAD

**Issue by boyney123** [winglang/wing#7088] opened 2024-09-09 09:23 UTC
### Use Case

I have some array, it would be nice to be able to sort it.

```
let x = [1, 10, 5];

// no sort method
x.sort();
```

### Proposed Solution

```
let x = [1, 10, 5];
x.sort(); // 1, 5, 10

Also allow a function as a param?
x.sort(sortFunc); 
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by skyrpex** [comment] 2024-09-09 09:32
Given the immutability nature that we're trying to achieve in Wing, maybe it'd make more sense if the array sort method returned a new sorted array:

```wing
let unsorted = [1, 10, 5];

let sorted = unsorted.sort();
```

Allow passing a compare function is a must, too 👍🏻.

**Comment by Chriscbr** [comment] 2024-09-11 18:44
Perhaps something like `array.sort()` for sorting in-place and `array.sorted()` for returning a shallow copy that has been sorted? (sorting in-place would only be allowed on `MutArray`)

**Comment by Chriscbr** [comment] 2024-09-11 18:44
Closing as duplicate of https://github.com/winglang/wing/issues/4998

**Closed by Chriscbr** 2024-09-11 18:44 UTC
Labels: ✨ enhancement, 🎨 sdk, needs-discussion
