### ISSUE TITLE
Cannot `str.fromJson()`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3989] opened 2023-08-29 05:42 UTC
### I tried this:

```
let obj = { "a": "b" };
let strJson = str.fromJson(obj);
```

### This happened:

```sh
$ wing test app.w
ERROR: unable to parse object [object Object] as a string

target/test/app.wsim.561026.tmp/.wing/preflight.js:14
       });
       const obj = ({"a": "b"});
>>     const strJson = ((args) => { if (typeof args !== "string") {throw new Error("unable to parse " + typeof args + " " + args + " as a string")}; return JSON.parse(JSON.stringify(args)) })(obj);
     }
   }
```

### I expected this:

I expected the `str.fromJson()` method to work.

### Component

Compiler

### Wing Version

0.26.3

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment] 2023-08-29 06:07
What's the purpose of `str.fromJson()` if we already have `Json.stringify()`? Do we really need two functions that do the same thing?

**Comment by WeepingClown13** [comment] 2023-08-29 06:21
This error makes sense to me reading the sdk implementation. `{  "a":"b" }` is not a string afterall and the `str.fromJson` method looks for a string. Rather, it'd be better to have some explicit mention of the function only working on Json strings if we decide to keep this method. Which again gets a bit confusing because combined with the log issue you opened, Json strings seems to simple strings which goes against the idea everything within a json is a json.

**Comment by garysassano** [comment] 2023-08-29 06:35
@WeepingClown13 Where did you see that `str.fromJson()` looks for a `String`? [Docs says otherwise](https://www.winglang.io/docs/standard-library/std/api-reference#fromjson--2).

![strfromjson](https://github.com/winglang/wing/assets/10464497/c053d0ef-d16b-41d5-8554-41558de47544)

**Comment by WeepingClown13** [comment] 2023-08-29 06:50
@garysassano yes it indeed takes json in wing. I meant the typescript implementation where it ensures the type is string and throws otherwise.

**Comment by garysassano** [comment] 2023-08-29 06:58
@WeepingClown13 You are right! https://github.com/winglang/wing/blob/main/libs/wingsdk/src/std/string.ts#L23

The code in the `@macro` expects a `String `input, while the actual method in TS/Wing expects a `Json` input.

**Comment by WeepingClown13** [comment] 2023-08-29 07:14
```ts
let obj = { "a": "b" };
let strJson = str.fromJson(obj.get("a"));
```

I am assuming this would probably work and give the output `"b"`. But nonetheless the docs would have to be more clear on the method's behaviours.

**Comment by garysassano** [comment] 2023-08-29 07:30
@WeepingClown13 The problem is that I don't think the VS Code extension would have a way to check if your `Json` object can be converted to a `String` and to show a warning if it cannot. Also, I personally don't feel the need of having a second method that does the same thing of `Json.stringify()`.

**Comment by MarkMcCulloh** [comment] 2023-08-29 13:21
- `str.fromJson` converts a Json value into the equivalent string. This is just a (checked) runtime cast, because the data stays exactly the same if successful.
- `Json.stringify` converts a Json value into a serialized string. This string is valid JSON. This means that a `Json.stringify("stuff")` would result in `"\"stuff\""`, not `"stuff"`

There has been discussion about this possible confusion before, I think there was consideration to rename the Json static methods to `Json.serialize` and `Json.deserialize` instead.

**Comment by hasanaburayyan** [comment] 2023-09-01 17:39
Yea to piggy back on what @MarkMcCulloh already mentioned I think we should maybe consider `Json.serialize` I think if I recall there was some push back but I dont remember vividly.
 
Either way I think we are safe to close this issue since the behavior is functioning as intended and behavior is documented. https://www.winglang.io/docs/language-reference

@staycoolcall911 maybe we can revisit the `stringify` vs `serialize` discussion in an upcoming team time?

**Closed by hasanaburayyan** 2023-09-01 17:39 UTC
Labels: 🐛 bug, 🛠️ compiler
