### ISSUE TITLE
Testing winglibs in the cloud automatically

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#6257] opened 2024-04-17 11:40 UTC
### Use Case

The libraries currently aren't tested in the cloud- therefore it's hard for us to ensure new PRs aren't breaking them, and the libraries are not guaranteed to work.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment] 2024-04-19 19:16
Duplicate of https://github.com/winglang/wing/issues/6251

**Comment by Chriscbr** [comment] 2024-04-19 19:24
Oops - I think I misread initially, since this is about running tests in actual cloud accounts (not just snapshotting outputs we can keep it separate.

**Closed** 2024-04-24 09:27 UTC
Labels: ✨ enhancement, needs-discussion, 📚 libraries

**Comment by tsuf239** [comment] 2024-04-24 09:45
The snapshots help us to know that the code can be compiled- but not if we missed a permission or two, or if our implementation is wrong for a certain use case, I think we should run them on the cloud if the snapshot changes- otherwise we can't ensure they are working as expected (unless we are really good at reading terraform- and I'm not- so I'll have to clone the contributor repo, and run the tests locally each time I'm reviewing a PR), I think it should be re-opened- unless there is a security/budget constraint/  we are delegating the "ensure that the code is actually working on the cloud" part to the creator of the library

**Comment by eladb** [comment] 2024-04-24 11:23
The difference between these snapshots and the ones taken with hangar is that in order update them users will need to actually run the test in the cloud. The snapshot reflects the result of a successful test.

See https://www.winglang.io/docs/tools/cli

**Comment by tsuf239** [comment] 2024-04-24 12:08
Nice! I didn't know :)
