### ISSUE TITLE
Ambiguous optional definition

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4440] opened 2023-10-06 12:30 UTC
### I tried this:

I'd like to define a struct property as an optional inflight method.

```ts
struct CookieSerializeOptions {
  domain: str?;
  encode: inflight (str): str?;
}

let s = CookieSerializeOptions {
  // Everything should be optional.
};
```

### This happened:

What gets converted to optional is the return type, not the `encode` property. So, this compile error happens:

```
Failed to compile.

error: "encode" is not initialized
  --> wing/main.w:6:9
  |  
6 |   let s = CookieSerializeOptions {
  | /---------^
7 | | 
8 | | };
  | \-^ "encode" is not initialized
```

### I expected this:

I need to be able to define that `encode` is optional.

Using parentheses around the `encode` definition doesn't help, as the compiler panics:

```ts
struct CookieSerializeOptions {
  domain: str?;
  encode: (inflight (str): str)?;
}

let s = CookieSerializeOptions {

};
```

The above panics with:

```
Failed to compile.

error: Expected function return type
  --> wing/main.w:3:11
  |
3 |   encode: (inflight (str): str)?;
  |           ^^^^^^^^^^^^^^^^^^^^^ Expected function return type


error: Compiler bug (panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/wingc/src/parser.rs:1523:34) during parsing, please report at https://www.winglang.io/contributing/start-here/bugs
  --> wing/main.w:1:1
  |  
1 | / struct CookieSerializeOptions {
2 | |   domain: str?;
3 | |   encode: (inflight (str): str)?;
4 | | }
  | \-^ Compiler bug (panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/wingc/src/parser.rs:1523:34) during parsing, please report at https://www.winglang.io/contributing/start-here/bugs
```

### Component

Language Design, Compiler

### Wing Version

0.35.5

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment] 2023-10-06 12:36
TypeScript allows using a question mark after the property name. An equivalent syntax in Wing would be:

```ts
struct CookieSerializeOptions {
  domain?: str;
  encode?: inflight (str): str;
}
```

With this syntax, we can also make the return type optional:

```ts
struct CookieSerializeOptions {
  domain?: str;
  encode?: inflight (str): str?;
}
```

**Comment by Chriscbr** [comment] 2023-10-06 17:29
Duplicate of https://github.com/winglang/wing/issues/4296

**Closed by Chriscbr** 2023-10-06 17:29 UTC
Labels: 🐛 bug
