### ISSUE TITLE
arguments in interface implementation are not enforced

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#4916] opened 2023-11-13 14:23 UTC
### I tried this:

```js
interface A {
   do(x: str): str;
}

class C impl A {
  pub do(): str {
    return "";
  }
}
```

### This happened:

code is compiling

### I expected this:

compile error for not implementing the `do(x: str)` method

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by yoav-steinberg** [comment] 2024-04-23 08:07
This is currently by design, note that if you change the example so the interface doesn't expect a param but the class does then you'll get the expected error:
```wing
interface A {
   do(): str;
}

class C impl A {
  pub do(x: str): str {
    return "";
  }
}
```
```
Error at main.w:6:7 | Expected type to be "preflight (): str", but got "preflight (x: str): str" instead
```
The reason is because we allow passing in a function with **less** parameters than expected by the interface so when implementing handlers we can easily ignore their parameters when we don't need them:
```wing
q.setConsumer(inflight () => { // Here we're ignoring the input `message` param
});
```
This is where we implement this behavior: https://github.com/winglang/wing/blob/fa4a7a5080bfedb3e85c015f1e7c0ee6468eafb0/libs/wingc/src/type_check.rs#L593

Some options to handling this:
1. Close this issue, and just stay with the current behavior.
2. Fix the current behavior to check fo the same number of parameters and not allow ignoring parameters in handlers.
3. For most cases do as 2 above, but add a specific exception when the type is an inflight closure (that's possibly going to be used as a handler).
4. Add a feature to our type system where you can flag a method in an interface as "doesn't require all parameters" and then anyone implementing that interface won't need to add all parameters to those methods. Then we'll set the handler interfaces in the SDK with that flag:
```ts
export interface IQueueSetConsumerHandlerClient {
  /**
   * Function that will be called when a message is received from the queue.
   * @inflight
   * @ignore_missing_params
   */
  handle(message: string): Promise<void>;
}
```
The type checker will will consider two functions the same if they have the same number of parameters or if one has less than the other and the other has this flag set.

**Comment by staycoolcall911** [comment] 2024-04-23 08:16
Let's go with option 1 - please reopen if you disagree.

An implementing class method can choose not to make usage of a parameter from the message signature, so it seems like a logical behavior to allow omitting it from the implementing class method signature altogether.
I discussed it before with EladB, Eyal and ShaiB - we should close this issue, this is ok.

**Closed by staycoolcall911** 2024-04-23 08:16 UTC
Labels: 🐛 bug, 📐 language-design, 🛠️ compiler, 🐶 dogfood

**Comment by Chriscbr** [comment] 2024-04-23 16:10
It will be good if we can document in the language reference (if we don't have it already) that parameters can only be omitted from the end of the list. e.g. 

```js
interface A {
   do(arg1: str, arg2: num): str;
}

class C impl A {
  pub do(arg2: num): str {
    return "";
  }
}
```

The above code isn't valid. Parameter names don't hold weight in Wing's type checker, in some sense.
