### ISSUE TITLE
Object property assignment shorthand doesn't work

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4261] opened 2023-09-22 08:34 UTC
### I tried this:

```ts
bring cloud;

let project = Json {
  id: "project_1",
  name: "acme",
};

new cloud.Function(inflight () => {
  // KO: {}
  log(Json.stringify({
    project,
  }));

  // OK: {"project":{"id":"project_1","name":"acme"}}
  log(Json.stringify({
    project: project,
  }));
});
```

### This happened:

The objects are empty when built this way:

```ts
return {
  project,
};
```

### I expected this:

Both examples should work the same.

### Is there a workaround?

No AFAIK.

### Component

Compiler

### Wing Version

0.32.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-09-22 17:20
Original issue for punning https://github.com/winglang/wing/issues/247

In the mean team, we should have a better error here because this:

```ts
{
  project,
};
```

Is actually a `Set<Json>`, which itself is not valid Json. 
IMO we should remove or change the set literal syntax.

**Comment by staycoolcall911** [comment] 2023-09-26 11:10
I'm closing this as duplicate of #247

**Closed by staycoolcall911** 2023-09-26 11:10 UTC
Labels: 🐛 bug
