### ISSUE TITLE
Can't pass method directly to ui.Button

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6241] opened 2024-04-15 18:58 UTC
### I tried this:

```js
bring cloud;
bring ui;

class Storage {
  data: cloud.Bucket;
  new() {
    this.data = new cloud.Bucket();
    new ui.Button("Add test file", this.addTestFile);
  }

  pub inflight addTestFile() {
    this.data.put("data.txt", "Hello, world!");
  }
}

new Storage();
```

### This happened:

The LSP does not show any error in the code, but when I compile the app I get the following error:

```
error: Cannot reference an inflight value from within a preflight expression
  --> main.w:8:36
  |
8 |     new ui.Button("Add test file", this.addTestFile);
  |                                    ^^^^^^^^^^^^^^^^ Cannot reference an inflight value from within a preflight expression
```

The error occurs the same if it's a static method:

```js
bring cloud;
bring ui;

let globalData = new cloud.Bucket();

class Helpers {
  pub static inflight addTestFile() {
    globalData.put("data.txt", "Hello, world!");
  }
}

class Storage {
  data: cloud.Bucket;
  new() {
    this.data = new cloud.Bucket();
    new ui.Button("Add test file", Helpers.addTestFile);
  }
}

new Storage();
```

### I expected this:

No error

### Is there a workaround?

Wrap the method in another function:

```
new ui.Button("Add test file", inflight () => { this.addTestFile(); });
```

### Wing Version

0.70.6

### Node.js Version

20.12.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2024-04-15 19:04
Dupe of https://github.com/winglang/wing/issues/3250

imo this issue is worthy enough to be in the stabilization milestone

**Closed by MarkMcCulloh** 2024-04-15 19:04 UTC
Labels: 🐛 bug, 🛠️ compiler
