### ISSUE TITLE
missing react dependencies

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4283] opened 2023-09-26 12:26 UTC
### I tried this:

PR build

### This happened:

I am seeing lots of errors like this:

```
React Hook useEffect has a missing dependency: 'onFetchDataUpdate'. Either include it or remove the dependency array. If 'onFetchDataUpdate' changes too often, find the parent component that defines it and wrap that definition in useCallback  
```

![Screenshot 2023-09-26 at 13 44 19](https://github.com/winglang/wing/assets/598796/0e820b1a-7d42-4dfc-a3b2-e952d5fc3a06)

### I expected this:

Not to see these errors

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-09-26 14:12
Dupe of https://github.com/winglang/wing/issues/3903

Also, PR open for fix https://github.com/winglang/wing/pull/4129

**Closed by MarkMcCulloh** 2023-09-26 14:12 UTC
Labels: 🐛 bug
