### ISSUE TITLE
Connection into hidden inner nodes should connect to parent (recursively)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6558] opened 2024-05-24 22:47 UTC
### I tried this:

```js
bring cloud;

class A {
  pub bucket: cloud.Bucket;
  new() {
    this.bucket = new cloud.Bucket();
  }
}

class B {
  pub a: A;
  new() {
    this.a = new A();
  }
}

let b1 = new B() as "B1";
let b2 = new B() as "B2";

new cloud.Function(inflight () => {
  b1.a.bucket.put("hello.txt", "world");
  b2.a.bucket.list();
});

nodeof(b1.a.bucket).hidden = true;
nodeof(b2.a).hidden = true;

```

### This happened:

<img width="196" alt="image" src="https://github.com/winglang/wing/assets/598796/d9666ede-a735-4a15-8715-7f6708a451af">

### I expected this:

I expected to see:

* A connection from `Function` to `B1/A` (with the .
* A connection from `Function` to `B2`.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2024-05-25 02:03
Dupe of #6523

**Closed by MarkMcCulloh** 2024-05-25 02:03 UTC
Labels: 🐛 bug
