### ISSUE TITLE
`cloud.Api` returns HTML error if no `status` is returned

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4723] opened 2023-10-30 16:34 UTC
### I tried this:

```ts
bring cloud;

let api = new cloud.Api();
api.post("/", inflight () => {});
```

### This happened:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read properties of undefined (reading &#39;status&#39;)<br> &nbsp; &nbsp;at isApiResponse (/app/node_modules/@winglang/sdk/lib/target-sim/api.inflight.js:128:22)<br> &nbsp; &nbsp;at /app/node_modules/@winglang/sdk/lib/target-sim/api.inflight.js:68:22</pre>
</body>
</html>
```

### I expected this:

Either:

- The request should return an empty response with status 200
- Shouldn't compile

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2023-10-30 19:26
I think this ought to be a compiler error. `api.post()` expects an `inflight (ApiRequest): ApiResponse`, and it's being passed a closure with an incompatible type, `inflight (): void`.

**Comment by eladb** [comment] 2023-10-31 00:20
I think all of these APIs should return optional types and then we should define a default behavior. For APIs this should be 200ok. 

@Chriscbr I remember we discussed this at some point, no?

**Comment by Chriscbr** [comment] 2023-10-31 01:55
oh, you're right - ignore my comment above 😅

**Comment by eladb** [comment] 2023-10-31 10:51
I believe this is a duplicate of https://github.com/winglang/wing/issues/4188 and I think we should prioritize that as P1

**Comment by staycoolcall911** [comment] 2023-10-31 12:24
Duplicate #4188

**Closed by staycoolcall911** 2023-10-31 12:24 UTC
Labels: 🐛 bug, 🎨 sdk, 🛠️ compiler, :dog: dogfood
