### ISSUE TITLE
Struct Literals need case conversion during Jsify

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#1917] opened 2023-03-27 14:42 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

let t = new cloud.Table(cloud.TableProps{name: "blah", columns: {id: cloud.ColumnType.STRING},  primary_key: "id"});
```
Then `wing compile -t sim app.w`

### I expected this:

Compile happily 😄 

### Instead, this happened:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/45375125/227973402-b29caa22-1aff-472b-b951-28dc355a3f35.png">

### Component:

Compiler

### Wing Version:

0.8.4

### Anything else?

The issue is that we do not convert `primary_key` back to camelCase during Jsification process. 

Here is the preflight.js generated, `primary_key` is snake case but the sdk api expects `camelCase`
```js
const t = this.node.root.newAbstract("@winglang/sdk.cloud.Table",this,"cloud.Table",{
  "name": "blah",
  "columns": Object.freeze({"id":cloud.ColumnType.STRING}),
  "primary_key": "id",}
  );
```
Spoke with @Chriscbr  about this and we need a way to know if a symbol requires the case conversion.

**Comment by staycoolcall911** [comment] 2023-03-28 06:52
duplicate of #1632

**Closed by staycoolcall911** 2023-03-28 06:52 UTC
Labels: bug, compiler
