### ISSUE TITLE
Completion issue

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5567] opened 2024-01-29 21:46 UTC
### I tried this:

```js
bring cloud;

let api = new cloud.Api();

api.post("/urls", inflight (req) => {
  req.
//    ^ cursor is here
  return { status: 200 };
});

```

### This happened:

<img width="611" alt="image" src="https://github.com/winglang/wing/assets/598796/09ccdb2e-ab0e-474e-be30-802c1593b1fc">

It seems like because there's `return` in the next line, the completion goes bad.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2024-01-29 21:47
Duplicate of https://github.com/winglang/wing/issues/5511

**Closed by Chriscbr** 2024-01-29 21:47 UTC
Labels: 🐛 bug
