### ISSUE TITLE
Impossible to declare recursive structs (or classes)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2917] opened 2023-06-14 12:26 UTC
### I tried this:

```js
struct Task {
  id: str;
  title: str;
  deps: Array<Task>;
}
```

### This happened:

```
Unknown symbol "Task"
```

### I expected this:

This should work.

### Is there a workaround?

In classes it is possible to use interfaces for this use case.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment] 2023-06-14 14:21
Duplicate of https://github.com/winglang/wing/issues/2648

**Closed by Chriscbr** 2023-06-14 14:21 UTC
Labels: 🐛 bug
