### ISSUE TITLE
can't run wing.compile to create a testing simulator and to a non testing simulator in the same process

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#5254] opened 2023-12-19 12:24 UTC
### I tried this:

in the same process of my node application, I'm trying to compile to a stateful simulator (non testing mode) and to a simulator runs in a testing mode.

```ts
const nonTestSim = await wing.compile(wingfile, {
        platform,
        testing: false,
      });
const testSim = await wing.compile(wingfile, {
        platform,
        testing: true,
      });
```

``` main.w
bring util;

if util.tryEnv("WING_IS_TEST") == "true" {
  log("Running in test mode");
} else {
  log("Not Running in test mode");
}
```

### This happened:

both simulators run in testing mode

### I expected this:

the first one to work in regular mode and the last one in testing mode.

### Anything else?

https://github.com/winglang/wing/blob/b5fa0cb75ee96d3ff19df59085d508240f5b0fd5/libs/wingcompiler/src/compile.ts#L158
if you run two compilers in the same process, the last one will override the process.envs with the latest values…
in the console we do exactly that:
https://github.com/winglang/wing/blob/b5fa0cb75ee96d3ff19df59085d508240f5b0fd5/apps/wing-console/console/server/src/index.ts#L116
and
https://github.com/winglang/wing/blob/b5fa0cb75ee96d3ff19df59085d508240f5b0fd5/apps/wing-console/console/server/src/index.ts#L136

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment] 2023-12-19 14:14
This is a dupe of https://github.com/winglang/wing/issues/3678 which will be addressed in https://github.com/winglang/wing/pull/5247

**Closed by MarkMcCulloh** 2023-12-19 14:14 UTC
Labels: 🐛 bug, 🕹️ simulator

**Comment by staycoolcall911** [comment] 2023-12-19 14:54
Thanks @MarkMcCulloh - since it's a blocker for @ainvoner, let's see if we can ship that fix earlier.
