### ISSUE TITLE
Compiler: Support static methods

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#1456] opened 2023-02-06 16:49 UTC
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

```typescript
let schedule = cloud.Schedule.fromCron("* * * * *");
```

Would like to allow invocation of static methods (Schedule namespace above)

### Use Cases

SDK spec for schedule
https://docs.winglang.io/reference/wingsdk-spec#schedule

### Component

Compiler

**Comment by Chriscbr** [comment] 2023-02-06 19:30
This might be a duplicate of #107 - though maybe we should close the other one since this issue has more context. cc @staycoolcall911

**Comment by staycoolcall911** [comment] 2023-02-06 20:11
Yes, this is a duplicate - I'd rather close this one since the other one is already prioritized and added on a few lists

**Closed** 2023-02-06 20:11 UTC
Labels: enhancement
