### ISSUE TITLE
Cannot call into preflight phase while inflight through a static method

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5253] opened 2023-12-19 10:08 UTC
### I tried this:

```js
bring cloud;

class MyClass {
  static makeBucket(scope: std.IResource): cloud.Bucket {
    return new cloud.Bucket() in scope;
  }

  inflight foo() {
    MyClass.makeBucket(this).put("foo.txt", "bar");
  }
}
```

### This happened:

```
Failed to compile.

error: Cannot call into preflight phase while inflight
  --> wing/main.w:9:5
  |
9 |     MyClass.makeBucket(this).put("foo.txt", "bar");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ Cannot call into preflight phase while inflight


```

### Is there a workaround?

Yes, if you call the static method in preflight and store the result, it works.

```js
bring cloud;

class MyClass {
  static makeBucket(scope: std.IResource): cloud.Bucket {
    return new cloud.Bucket() in scope;
  }

  b: cloud.Bucket;

  new() {
    this.b = MyClass.makeBucket(this);
  }

  inflight foo() {
    this.b.put("foo.txt", "bar");
  }
}
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by yoav-steinberg** [comment] 2023-12-19 20:24
Some clarifications:
In theory any _preflight_ expression can be "lifted" and therefore any preflight expression can be used _inflight_.
So these two chunks are the same:
```wing
let b = new cloud.Bucket();
inflight () => {
  b.list();
}
```
and
```
inflight () => {
  (new cloud.Bucket()).list();
}
```
The reason we'll get `Cannot create preflight class "Bucket" in inflight phase` the latter or the similar `Cannot call into preflight...` are because during type checking we added explicit code prohibiting this. There's a chance we can remove these checks and all will be well. But since the lifting code is a bit shaky anyway I suggest waiting a bit before doing so.

**Comment by staycoolcall911** [comment] 2023-12-24 11:45
Ok, so this is by design. @eladb - do you want to keep this issue open?

**Comment by staycoolcall911** [comment] 2023-12-24 16:37
Closing for now.

**Closed by staycoolcall911** 2023-12-24 16:37 UTC
Labels: 🐛 bug, needs-discussion
